apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection-deployment
  labels:
    app: fraud-detection
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
      - name: fraud-detection-api
        image: fraud-detection-api:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: MODEL_PATH
          value: "model/fraud_model.pkl"
        - name: SCALER_PATH
          value: "model/scaler.pkl"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
